// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAishDhppB4xPrBMsT3zuASRboXp2ZTEPo',
    appId: '1:1023054501122:web:737d3663f851e8936a1e1b',
    messagingSenderId: '1023054501122',
    projectId: 'rently-545da',
    authDomain: 'rently-545da.firebaseapp.com',
    storageBucket: 'rently-545da.firebasestorage.app',
    measurementId: 'G-KQHK3N9P2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Yvs86Gu__u0ofrKLmGPHh4NxnW6hImo',
    appId: '1:1023054501122:android:10d4827fbcfd6fe96a1e1b',
    messagingSenderId: '1023054501122',
    projectId: 'rently-545da',
    storageBucket: 'rently-545da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCySeTp1DnyNItPW-GLImvohKKQZq2KXUA',
    appId: '1:1023054501122:ios:e76be79872a2f72b6a1e1b',
    messagingSenderId: '1023054501122',
    projectId: 'rently-545da',
    storageBucket: 'rently-545da.firebasestorage.app',
    iosBundleId: 'com.example.rentlyCse2100Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCySeTp1DnyNItPW-GLImvohKKQZq2KXUA',
    appId: '1:1023054501122:ios:e76be79872a2f72b6a1e1b',
    messagingSenderId: '1023054501122',
    projectId: 'rently-545da',
    storageBucket: 'rently-545da.firebasestorage.app',
    iosBundleId: 'com.example.rentlyCse2100Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAishDhppB4xPrBMsT3zuASRboXp2ZTEPo',
    appId: '1:1023054501122:web:2faa1477643ba4596a1e1b',
    messagingSenderId: '1023054501122',
    projectId: 'rently-545da',
    authDomain: 'rently-545da.firebaseapp.com',
    storageBucket: 'rently-545da.firebasestorage.app',
    measurementId: 'G-GB99YRFY1S',
  );
}
